version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=api.listail.org
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=api.listail.org
    networks:
      - default
      - nginx-netork
  
networks:
  nginx-network:
    external: true